### ISSUE TITLE
Several errors when running must-gather

### ISSUE THREAD

**Issue by yossisegev** [openshift/must-gather#119]
When running must-gather - the actions fails, specifying the following errors:
```
$ oc adm must-gather
namespace/openshift-must-gather-pw995 created
clusterrolebinding.rbac.authorization.k8s.io/must-gather-n7jvb created
container logs unavailable: Get https://host-172-16-0-21:10250/containerLogs/openshift-must-gather-pw995/must-gather-2k9gh/gather?follow=true: remote error: tls: internal errorWARNING: cannot use rsync: rsync not available in container
WARNING: cannot use tar: tar not available in container
clusterrolebinding.rbac.authorization.k8s.io/must-gather-n7jvb deleted
namespace/openshift-must-gather-pw995 deleted
error: No available strategies to copy.
```

Running on a cluster with openshift 4.2 installed.

**Comment by duyanyan** [comment]
$ oc version
Client Version: version.Info{Major:"4", Minor:"2+", GitVersion:"v4.2.0", GitCommit:"b985ea310", GitTreeState:"clean", BuildDate:"2019-08-26T23:02:57Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.0+8b7397d", GitCommit:"8b7397d", GitTreeState:"clean", BuildDate:"2019-08-28T02:56:43Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
OpenShift Version: 4.2.0-0.nightly-2019-08-28-035628


And I think it is not related to the must gather, the root cause is "oc logs" not working well
$ oc logs hco-operator-6d8bb86d87-jjz94
Error from server: Get https://host-172-16-0-24:10250/containerLogs/openshift-cnv/hco-operator-6d8bb86d87-jjz94/hyperconverged-cluster-operator: remote error: tls: internal error
